@baseUrl = http://localhost:4000
@ruralProducerId = clreby7oq00001xai7onpehru

# @name create_rural_producer
POST {{baseUrl}}/rural-producers
Content-Type: application/json

{
  "name": "Seu Zé",
  "cpfCnpj": "123.456.789-01",
  "farm": "Fazenda São João",
  "city": "São Paulo",
  "state": "SP",
  "totalArea": 310.5,
  "arableArea": 200,
  "vegetationArea": 110.5,
  "cropIds": ["clre9pcoh00033b6ob25hopa1", "clre9pcon001p3b6oekx7spxy"]
}

###

# @name list_rural_producers
GET {{baseUrl}}/rural-producers

###

# @name update_rural_producer
PUT {{baseUrl}}/rural-producers/{{ruralProducerId}}
Content-Type: application/json

{
  "name": "Seu Zezinho",
  "cropIds": ["clre9pcoh00033b6ob25hopa1"]
}